from .instructions import get_sophia_instructions
from .singletons import (
    _get_episodic,
    _get_failure_memory,
    _get_goals,
    _get_loader,
    _get_mapper,
    _get_meta,
    _get_monitor,
    _get_procedural,
    _get_pruner,
    _get_reflection,
    _get_semantic,
    _get_spatial,
    _get_store,
    _get_sweeper,
    _get_temporal,
    _get_visual,
)
from .text_utils import extract_first_json_block, extract_tool_calls, strip_thinking_block

__all__ = [
    "_get_episodic",
    "_get_failure_memory",
    "_get_goals",
    "_get_loader",
    "_get_mapper",
    "_get_meta",
    "_get_monitor",
    "_get_procedural",
    "_get_pruner",
    "_get_reflection",
    "_get_semantic",
    "_get_spatial",
    "_get_store",
    "_get_sweeper",
    "_get_temporal",
    "_get_visual",
    "extract_first_json_block",
    "extract_tool_calls",
    "get_sophia_instructions",
    "strip_thinking_block",
]
