"""initial_schema_consolidation_v2

Revision ID: 4f4418aa5ad9
Revises:
Create Date: 2026-05-15 21:05:26.252605

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f4418aa5ad9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_exp_agent", "agent_experience", ["agent_id", "task_pattern"], unique=False)
    op.create_index("idx_agent_timestamp", "episodes", ["agent_id", "created_at"], unique=False)
    op.create_index("idx_episodes_session", "episodes", ["session_id"], unique=False)
    with op.batch_alter_table("events") as batch_op:
        batch_op.alter_column(
            "event_type",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=100),
            existing_nullable=False,
        )
    op.create_index("idx_events_session", "events", ["session_id"], unique=False)
    op.create_index("idx_rel_subject", "facts", ["subject"], unique=False)
    op.create_index("idx_goals_active", "goals", ["status", "priority"], unique=False)
    with op.batch_alter_table("meta_cognition") as batch_op:
        batch_op.alter_column(
            "session_id",
            existing_type=sa.TEXT(),
            type_=sa.String(length=100),
            existing_nullable=True,
            existing_server_default=sa.text("('')"),
        )
    op.create_index("idx_refl_session", "meta_cognition", ["session_id"], unique=False)
    with op.batch_alter_table("operational_logs_v2") as batch_op:
        batch_op.alter_column(
            "session_id",
            existing_type=sa.TEXT(),
            type_=sa.String(length=100),
            existing_nullable=True,
            existing_server_default=sa.text("'default'"),
        )
    op.create_index("idx_tool_paths_task", "tool_paths", ["task_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tool_paths_task", table_name="tool_paths")
    op.alter_column(
        "operational_logs_v2",
        "session_id",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
        existing_server_default=sa.text("'default'"),
    )
    op.drop_index("idx_refl_session", table_name="meta_cognition")
    op.alter_column(
        "meta_cognition",
        "session_id",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
        existing_server_default=sa.text("('')"),
    )
    op.drop_index("idx_goals_active", table_name="goals")
    op.drop_index("idx_rel_subject", table_name="facts")
    op.drop_index("idx_events_session", table_name="events")
    op.alter_column(
        "events",
        "event_type",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_index("idx_episodes_session", table_name="episodes")
    op.drop_index("idx_agent_timestamp", table_name="episodes")
    op.drop_index("idx_exp_agent", table_name="agent_experience")
    # ### end Alembic commands ###
